[application]

# App name
name = "ORE"

# Default platform
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

asset_dir = "public"

[package]
name = "ORE"

[web.app]

# HTML title tag content
title = ""

[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = true
# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]
# resolves a hot reloading issue
index_on_404 = true

[bundle]
publisher = "Regolith Labs Inc."
identifier = "ore.supply"
## https://v1.tauri.app/v1/guides/features/icons/
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]

[bundle.windows]
icon_path = "icons/icon.ico"
tsp = false
allow_downgrades = true
[bundle.windows.webview_install_mode.EmbedBootstrapper]
silent = true
