[application]
name = "ORE"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[package]
name = "ORE"

[web.app]
title = ""

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = true

[bundle]
publisher = "Regolith Labs Inc."
identifier = "ore.supply"
icon = ["public/icon.png"]

[macos]
info_plist_path = "Info.plist"

