use dioxus::prelude::*;

use crate::components::*;

use super::*;

pub fn StakingContent() -> Element {
    rsx! {
        ContentSection {
            StakingIntro {}
            StakingHowItWorks {}
            StakingFaq {}
        }
    }
}

fn StakingIntro() -> Element {
    rsx! {
        span {
            span {
                class: "font-semibold text-elements-highEmphasis",
                "Staking offers yield to liquidity providers for making markets more efficient for traders. "
            }
            "These incentives help offset the risk that liquidity providers inherently take on by creating better markets."
        }
    }
}

fn StakingHowItWorks() -> Element {
    rsx! {
        SectionTitle {
            "How it works"
        }
        BulletPointList {
            BulletPoint {
                "Boosts are a feature that allow the governance community to fund growth initiatives such as marketing, development, and liquidity with protocol emissions."
            }
            BulletPoint {
                "Yield is generated by automatically directing a slice of all newly mined supply to boosts. These funds come from the existing token emissions schedule, and do not produce any additional inflation for holders."
            }
            BulletPoint {
                "A number of current boosts target liquidity providers to help bootstrap liquidity for the token. LPs can earn yield by making ORE markets more efficient and strengthening the value of the currency."
            }
        }
    }
}

fn StakingFaq() -> Element {
    rsx! {
        SectionTitle {
            "FAQ"
        }
        Col {
            class: "md:flex-row w-full h-min mx-auto max-w-7xl justify-start",
            Col {
                class: "w-full h-min justify-start",
                FaqItem {
                    question: "Will there be more boosts?",
                    "Yes, the ORE community is actively involved in proposing and managing boost incentives. "
                    Link {
                        new_tab: true,
                        to: "https://discord.gg/4TQfshAAsT",
                        span { class: "text-elements-gold hover:underline font-medium", "Join the Discord" }
                    }
                    " to stay up to date and get involved in the ORE boost governance process."
                }
                FaqItem {
                    question: "Why does the APR change?",
                    "APR is calculated based on a 7-day rolling average. As more assets are staked in a boost, the yield is split among more participants, causing the APR to decrease. Conversely, if the total staked amount goes down, the APR will rise.",
                }
                FaqItem {
                    question: "Are there risks to providing liquidity?",
                    "Yes, providing liquidity comes with inherent financial risk, including but not limited to divergence loss. Divergence loss occurs when the relative price of deposited tokens changes, potentially reducing the value of the deposit compared to simply holding the tokens separately. Once deposited, your exposure to each token may change depending on market conditions."
                }
            }
        }
    }
}
