[package]
name = "ore-app-serve"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
ore-miner = { git = "https://github.com/regolith-labs/ore-pool-private", package = "ore-miner", branch = "master" }