[package]
name = "wallet-adapter-android"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21.1" # Use the latest appropriate version

[lib]
crate-type = ["cdylib"]
name = "wallet_adapter_android"

# Removed build-dependencies and bin sections related to uniffi
