pools:
  - address: 9RrEyMNFhFcrqVikWby5rVn1eXeKHr2SwGRbPhZ7wDCK
    url: https://official.ec1ipse.me
    name: Ec1ipse
    description: ""
    image: https://pbs.twimg.com/profile_images/1736827532312211456/V0bvyS_2_400x400.jpg

  - address: 4JZYE9NJSXdnHYdB7PQzzyxGqm6ALp2t39bXFe9iNr3F
    url: https://ore-pool.onrender.com
    name: ORE Pool
    description: ""
    image: "" 
  
  # - address: DrSS5RM7zUd9qjUEdDaf31vnDUSbCrMto6mjqTrHFifN
  #   url: ""
  #   name: Rush
  #   description: ""
  #   image: https://pbs.twimg.com/profile_images/1825694276929368064/GJcGr3rR_400x400.jpg
