boosts:
  - address: 48J2TSpVpwmrwW84sMERcZigeAeFuUnC8bKHp7ET6RXt
    pair_mint: So11111111111111111111111111111111111111112
    lp_mint: 8H8rPiWW4iTFCfEkSnf7jpqeNpFfvdH9gLouAL3Fe2Zx
    lp_id: 6TFdY15Mxty9sRCtzMXG8eHSbZy4oiAEQUvLQdz9YwEn
    lp_type: kamino 
    name: SOL-ORE Kamino LP
    ticker: kSOL-ORE
    lut: RtzNY3VVuJHteXtF22v3ctLiksttnMSTLfgPFzyFDz2

  - address: D4qtrWeNpJnZpmT9Fe2kx5oJf3E4ovorZgE6K6ux7Lqt
    pair_mint: So11111111111111111111111111111111111111112
    lp_mint: DrSS5RM7zUd9qjUEdDaf31vnDUSbCrMto6mjqTrHFifN
    lp_id: GgaDTFbqdgjoZz3FP7zrtofGwnRS4E6MCzmmD5Ni1Mxj
    lp_type: meteora
    name: SOL-ORE Meteora LP
    ticker: SOL-ORE MLP
    lut:

  - address: EExSorxnhxVKqnhNT4dNPNa8zvRBNBgju6n91F9cnKKy
    lp_mint: 7G3dfZkSk1HpDGnyL37LMBbPEgT4Ca6vZmZPUyi2syWt
    pair_mint: hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux 
    lp_id: 9XsAPjk1yp4U6hKZj9r9szhcxBi3RidGuyxiC2Y8JtAe
    lp_type: kamino
    name: HNT-ORE Kamino LP
    ticker: kHNT-ORE
    lut: G9aqZtDcXYYzocyVMcsd4j2m3ootcb1kKNvTXciwJLQN

  - address: A2Sb1oxg2H3ecbAHaJFXccufyC7pD1CMEakJhcz2TeH9
    lp_mint: 9BAWwtAZiF4XJC6vArPM8JhtgKXfeoeo9FJHeR3PEGac
    pair_mint: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    lp_id: 7XNR3Ysqg2MbfQX8iMWD4iEF96h2GMsWNT8eZYsLTmua
    lp_type: meteora
    name: ORE-USDC Meteora LP
    ticker: ORE-USDC MLP
    lut:
